#!/bin/bash -ev

CURRENT_DIRECTORY=`dirname $(realpath $0)`
SCRIPTS_DIRECTORY=$CURRENT_DIRECTORY/scripts

. $SCRIPTS_DIRECTORY/ubuntu-install-packages

. $SCRIPTS_DIRECTORY/git-load-utility-functions
. $SCRIPTS_DIRECTORY/git-clone-public-repositories
. $SCRIPTS_DIRECTORY/git-clone-private-repositories

