#!/bin/bash -ev

CURRENT_DIRECTORY=`dirname $(realpath $0)`
SCRIPTS_DIRECTORY=$CURRENT_DIRECTORY/scripts

. $SCRIPTS_DIRECTORY/ubuntu-installations

. $SCRIPTS_DIRECTORY/gpg-import

. $SCRIPTS_DIRECTORY/git-clone
. $SCRIPTS_DIRECTORY/git-configure

