#!/bin/bash -ev


CURRENT_DIRECTORY=`dirname -- $(readlink -f -- $BASH_SOURCE)`
PERSONAL_DIRECTORY=~/Repositories/personal

# > public-dotfiles

fl_git_clone_bare_repository https://gitlab.com/fabianolothor/public-dotfiles.git $PERSONAL_DIRECTORY/public-dotfiles

ln -fs "$CURRENT_DIRECTORY/../../../public-dotfiles/main/.bash_profile" ~/.bash_profile -vvv
. ~/.bashrc

. $CURRENT_DIRECTORY/gpg-import-key

# < public-dotfiles

