#!/bin/bash -ev

fl_git_clone_bare_repository() {
    git clone --bare $1 $2/.git
    fl_git_configure_bare_repository $2
}

fl_git_configure_bare_repository() {
    git -C $1 config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git -C $1 fetch
}

