#!/bin/bash -ev

SUDO="$(sudo --version >/dev/null 2>&1 && echo 'sudo' || echo '')"

$SUDO apt -y update ; $SUDO apt -y upgrade

$SUDO apt -y install \
    curl \
    findutils fonts-firacode \
    git-gui gpg \
    jq \
    parallel pass \
    sudo \
    tmux \
    vim

